# Generated by Django 4.1.5 on 2023-07-15 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_user_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='select',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='upload',
            name='username',
            field=models.CharField(default='no', max_length=50),
        ),
    ]
