# Generated by Django 4.1.5 on 2023-09-26 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0035_user_database"),
    ]

    operations = [
        migrations.CreateModel(
            name="reporter_img",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("news_id", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="img/%y")),
                ("username", models.CharField(default="username", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="upload_news",
            fields=[
                (
                    "news_id",
                    models.AutoField(default="0000", primary_key=True, serialize=False),
                ),
                ("heading", models.CharField(max_length=50)),
                ("content", models.CharField(max_length=10000)),
                ("created_date", models.DateField(default=datetime.date(2023, 9, 26))),
                ("modify_date", models.DateField(default=datetime.date(2023, 9, 26))),
                ("status", models.CharField(default="1", max_length=50)),
                ("username", models.CharField(default="username", max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name="login",
        ),
        migrations.DeleteModel(
            name="reporter",
        ),
        migrations.DeleteModel(
            name="upload",
        ),
        migrations.DeleteModel(
            name="user_data",
        ),
    ]
