# Generated by Django 4.1.5 on 2023-07-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_upload_select_upload_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
        migrations.DeleteModel(
            name='reporter',
        ),
        migrations.DeleteModel(
            name='user_data',
        ),
        migrations.AlterField(
            model_name='upload',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
