# Generated by Django 4.1.5 on 2023-09-26 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0036_reporter_img_upload_news_delete_login_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reporter_img",
            name="news_id",
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name="upload_news",
            name="created_date",
            field=models.DateField(default=datetime.date(2023, 9, 27)),
        ),
        migrations.AlterField(
            model_name="upload_news",
            name="modify_date",
            field=models.DateField(default=datetime.date(2023, 9, 27)),
        ),
        migrations.AlterField(
            model_name="upload_news",
            name="news_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
