# Generated by Django 4.1.5 on 2023-09-27 04:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0037_alter_reporter_img_news_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user_database",
            old_name="adress",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="user_database",
            old_name="collage",
            new_name="college",
        ),
        migrations.RenameField(
            model_name="user_database",
            old_name="midlename",
            new_name="middlename",
        ),
    ]
