# Generated by Django 4.1.5 on 2023-07-16 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_delete_login_delete_reporter_delete_user_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='report_image',
            fields=[
                ('image', models.ImageField(upload_to='img/%y')),
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='upload_news',
            fields=[
                ('primary_key', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=10000)),
                ('created_date', models.DateField(default=datetime.date(2023, 7, 17))),
                ('modify_date', models.DateField(default=datetime.date(2023, 7, 17))),
                ('status', models.CharField(default='1', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='upload',
        ),
    ]
