# Generated by Django 4.1.5 on 2023-11-20 02:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0038_rename_adress_user_database_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload_news",
            name="news_type",
            field=models.CharField(default="news", max_length=50),
        ),
        migrations.AlterField(
            model_name="upload_news",
            name="created_date",
            field=models.DateField(default=datetime.date(2023, 11, 20)),
        ),
        migrations.AlterField(
            model_name="upload_news",
            name="modify_date",
            field=models.DateField(default=datetime.date(2023, 11, 20)),
        ),
    ]
