# Generated by Django 4.1.5 on 2023-07-17 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_report_image_upload_news_delete_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_news',
            name='username',
            field=models.CharField(default='username', max_length=50),
        ),
        migrations.AlterField(
            model_name='upload_news',
            name='created_date',
            field=models.DateField(default=datetime.date(2023, 7, 18)),
        ),
        migrations.AlterField(
            model_name='upload_news',
            name='modify_date',
            field=models.DateField(default=datetime.date(2023, 7, 18)),
        ),
    ]
