# Generated by Django 4.1.7 on 2023-11-29 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0039_upload_news_news_type_alter_upload_news_created_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_database",
            name="address",
        ),
        migrations.RemoveField(
            model_name="user_database",
            name="college",
        ),
        migrations.RemoveField(
            model_name="user_database",
            name="qualification",
        ),
        migrations.RemoveField(
            model_name="user_database",
            name="school",
        ),
        migrations.AlterField(
            model_name="upload_news",
            name="created_date",
            field=models.DateField(default=datetime.date(2023, 11, 29)),
        ),
        migrations.AlterField(
            model_name="upload_news",
            name="modify_date",
            field=models.DateField(default=datetime.date(2023, 11, 29)),
        ),
    ]
