# Generated by Django 4.1.5 on 2023-07-26 12:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_report_image_key_alter_upload_news_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_image',
            name='key',
        ),
        migrations.AddField(
            model_name='report_image',
            name='id',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='home.upload_news'),
        ),
        migrations.AlterField(
            model_name='upload_news',
            name='created_date',
            field=models.DateField(default=datetime.date(2023, 7, 26)),
        ),
        migrations.AlterField(
            model_name='upload_news',
            name='modify_date',
            field=models.DateField(default=datetime.date(2023, 7, 26)),
        ),
    ]
