# Generated by Django 4.1.5 on 2023-12-05 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0040_remove_user_database_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reporter_img",
            name="image",
            field=models.FileField(upload_to="img/%y"),
        ),
        migrations.AlterField(
            model_name="upload_news",
            name="created_date",
            field=models.DateField(default=datetime.date(2023, 12, 5)),
        ),
        migrations.AlterField(
            model_name="upload_news",
            name="modify_date",
            field=models.DateField(default=datetime.date(2023, 12, 5)),
        ),
    ]
