# Generated by Django 4.1.5 on 2023-12-05 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0041_alter_reporter_img_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="advertisement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.FileField(upload_to="img/%y")),
                ("username", models.CharField(default="username", max_length=50)),
                ("company_name", models.CharField(default="username", max_length=50)),
                ("created_date", models.DateField(default=datetime.date(2023, 12, 5))),
                ("modify_date", models.DateField(default=datetime.date(2023, 12, 5))),
            ],
        ),
    ]
