# Generated by Django 4.1.5 on 2023-07-26 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_alter_report_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_image',
            name='id',
        ),
    ]
