# Generated by Django 4.1.5 on 2023-07-29 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_remove_report_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_news',
            name='created_date',
            field=models.DateField(default=datetime.date(2023, 7, 29)),
        ),
        migrations.AlterField(
            model_name='upload_news',
            name='modify_date',
            field=models.DateField(default=datetime.date(2023, 7, 29)),
        ),
    ]
