# Generated by Django 4.1.5 on 2023-07-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_alter_upload_news_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_image',
            name='primary_key',
            field=models.AutoField(default='00000', primary_key=True, serialize=False),
        ),
    ]
