# Generated by Django 4.1.5 on 2023-07-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_alter_report_image_primary_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_image',
            name='primary_key',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
